FROM debian:bookworm AS butano

WORKDIR /butano

# downloads butano
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/GValiente/butano.git
# patches butano
RUN wget -O /butano/tools/common_setup.mak https://raw.githubusercontent.com/Luapree/patito-cuac-cuac-ds/refs/heads/main/patches/common_setup.mak

FROM devkitpro/devkitarm:latest AS main_builder
WORKDIR /app
COPY --from=butano /butano /butano

# builds the binary
COPY . .
RUN make PLATFORM=gba

FROM scratch AS exporter
COPY --from=main_builder /app/patito-cuac-cuac-gba.gba /patito-cuac-cuac-gba.gba